title: Dhrumil Mehta

exclude: [screenshots, LICENSE, README.md]
markdown: kramdown

buttons:
 - text: Home
   url: /
 - text: Journalism
   url: journalism
 - text: Research
   url: research
 - text: Teaching
   url: teaching
 - text: Media
   url: media

social:
  - type: email
    value: mailto:dhrumil.mehta@columbia.edu
    class: envelope-o
  - type: github
    value: https://github.com/dmil
    class: github
  - type: linkedin
    value: https://linkedin.com/in/dhrumilmehta
    class: linkedin
  - type: twitter
    value: https://twitter.com/datadhrumil
    class: twitter
  - type: medium
    value: https://medium.com/@DataDhrumil
    class: medium

